#!/usr/bin/env python
import os
import sys
import pathlib as pb

env = SConscript(".godot-cpp/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
extPath = pb.Path('extensions')
extSrc = str(extPath / 'src')
extOut = str(extPath / 'bin')

env.Append(CPPPATH=[extSrc])
sources = Glob(f'{extSrc}/*.cpp')

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{}/libgdexample.{}.{}.framework/libgdexample.{}.{}".format(
            extOut, env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "{}/libgdexample{}{}".format(
            extOut, env["suffix"], env["SHLIBSUFFIX"]
        ),
        source=sources,
    )

Default(library)
